coverage_service: cobertura_xml
scheme: testapp
xcodeproj: Example/devices.xcodeproj
workspace: devices.xcworkspace
source_directory: LibraryComponents
output_directory: coverage
ignore:
 - ../**/*/Xcode*
 - Example/*
 - Pods/*
