version: 2.1

parameters:
  type:
    type: enum
    enum: ["ci", "build", "default"]
    default: "default"
  build_context:
      type: string
      default: ''
orbs:
  meli: mercadolibre/ios@volatile
default-workflow: &defaultWorkflow
  filters:
    branches:
      ignore:
        - master
        - /release\/.*$/
        - /v\/.*$/
workflows:
  ci:
    jobs:
      - meli/test:
          <<: *defaultWorkflow
      - meli/lint:
          <<: *defaultWorkflow
  build:
    when:
      equal: [build, << pipeline.parameters.type >>] 
    jobs:
      - meli/build
